### ISSUE TITLE
 undefined method `services' for Celluloid:Module

### ISSUE THREAD

**Issue by bogdanRada** [celluloid/celluloid-pool#10]
Hello, i am trying to use celluloid 0.17.1.1 version and i have this class 

```ruby
  class Worker
     include Celluloid
  end
```

I get this error when trying to execute this: 
```ruby
Worker.pool(size: 10) 
```

and here is the backtrace:

```
gems/celluloid-supervision-0.20.1/lib/celluloid/supervision/deprecate/supervise.rb:54:in `router'
  gems/celluloid-supervision-0.20.1/lib/celluloid/supervision/deprecate/supervise.rb:6:in `supervise'
gems/celluloid-pool-0.20.0/lib/celluloid/supervision/container/behavior/pool.rb:13:in `pool'
```

And this my Gemfile.lock:
```
    celluloid (0.17.1.1)
      bundler
      celluloid-essentials
      celluloid-extras
      celluloid-fsm
      celluloid-pool
      celluloid-supervision
      dotenv
      nenv
      rspec-logsplit (>= 0.1.2)
      timers (~> 4.0.0)
    celluloid-essentials (0.20.2)
      bundler
      dotenv
      nenv
      rspec-logsplit (>= 0.1.2)
      timers (~> 4.0.0)
    celluloid-extras (0.20.0)
      bundler
      dotenv
      nenv
      rspec-logsplit (>= 0.1.2)
      timers (~> 4.0.0)
    celluloid-fsm (0.20.0)
      bundler
      dotenv
      nenv
      rspec-logsplit (>= 0.1.2)
      timers (~> 4.0.0)
    celluloid-pool (0.20.0)
      bundler
      dotenv
      nenv
      rspec-logsplit (>= 0.1.2)
      timers (~> 4.0.0)
    celluloid-supervision (0.20.1)
      bundler
      dotenv
      nenv
      rspec-logsplit (>= 0.1.2)
      timers (~> 4.0.0)
  coderay (1.1.0)
    diff-lcs (1.2.5)
    dotenv (2.0.2)
    hitimes (1.2.2)
    method_source (0.8.2)
    nenv (0.2.0)

PLATFORMS
  ruby
```

can you please tell me what am i doing wrong? can't figure this out.

**Comment by digitalextremist** [comment]
Did you use `require 'celluloid/current'` rather than just `celluloid`?

This should not be happening to you and I will look at why, but for now, can you try that?

**Comment by bogdanRada** [comment]
yep...sorry. that fixes it. Forgot about that. Thank you very much.

**Comment by digitalextremist** [comment]
No problem. I will add `Celluloid.services` to `deprecate.rb` for others.

**Comment by edebill** [comment]
I still ran into this on latest (0.17.3) celluloid, with celluloid-pool (0.20.5). require "celluloid/current" was the the fix.
